### PR TITLE
Fix typo of `memory_efficient_fusion` parameter

### PR DESCRIPTION
**Pull request by hyunwoongko**
This causes some problems about input shape.

### CODE REVIEW

**Review by Chillee — APPROVED** [review]
Hmm... I think it defaults to StaticShapeHasher if it doesn't match anything, but nice catch!

**Comment by hyunwoongko** [comment]
@Chillee When I test, when a new shape is input, it is not hashed and a size error occurs. You can test it by this script.

- testcase 1
```python
import torch

from functorch.compile.aot_autograd import aot_function
from functorch.compile.compilers import ts_compile, default_decompositions
from transformers.models.bert.modeling_bert import BertEmbeddings, BertConfig

emb = BertEmbeddings(BertConfig.from_pretrained("bert-base-cased"))

config = {
    "fw_compiler": ts_compile,
    "bw_compiler": ts_compile,
    "hasher_type": "StaticShapeHasher",
    "decompositions": default_decompositions,
}

traced = aot_function(emb.forward, **config)
inputs = {"input_ids": torch.tensor([[1, 2, 3, 4]]).long()}
output = traced(**inputs)

inputs = {"input_ids": torch.tensor([[1, 2, 3, 4, 5]]).long()}
output = traced(**inputs)
```
```
Work
```

<br><br>

- testcase 2

```python
import torch

from functorch.compile.aot_autograd import aot_function
from functorch.compile.compilers import ts_compile, default_decompositions
from transformers.models.bert.modeling_bert import BertEmbeddings, BertConfig

emb = BertEmbeddings(BertConfig.from_pretrained("bert-base-cased"))

config = {
    "fw_compiler": ts_compile,
    "bw_compiler": ts_compile,
    "hasher_type": "StaticShapheHasher",
    "decompositions": default_decompositions,
}

traced = aot_function(emb.forward, **config)
inputs = {"input_ids": torch.tensor([[1, 2, 3, 4]]).long()}
output = traced(**inputs)

inputs = {"input_ids": torch.tensor([[1, 2, 3, 4, 5]]).long()}
output = traced(**inputs)
```
```
  File "<eval_with_key>.3", line 8, in fallback_function
    embedding = torch.ops.aten.embedding(_param_constant0, primals_1, 0);  _param_constant0 = primals_1 = None
    _tensor_constant0 = self._tensor_constant0
    add = torch.ops.aten.add(embedding, _tensor_constant0);  embedding = _tensor_constant0 = None
          ~~~~~~~~~~~~~~~~~~ <--- HERE
    _tensor_constant1 = self._tensor_constant1
    add_ = torch.ops.aten.add_(add, _tensor_constant1);  add = _tensor_constant1 = None
RuntimeError: The size of tensor a (5) must match the size of tensor b (4) at non-singleton dimension 1
```

**Comment by anijain2305** [comment]
Thanks. Good catch!

**Comment by Chillee** [comment]
@hyunwoongko oops, i think you're right.  Will file an issue to raise an error when that happens.

**Pull request merged**
